version: '3'
services:

  app:
    image: figured/php-dev:8.0
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "TZ=Pacific/Auckland"

  web:
    image: nginx:stable
    working_dir: /var/www
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./:/var/www
    ports:
      - 1515:80

  database:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=figured_test"
      - "MYSQL_USER=figured_user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "33061:3306"

volumes:
  mysql:
    driver: local
